### ISSUE TITLE
Error on npm start command

### ISSUE THREAD

**Issue by caioquirino** [iquirino/LogEngine#1]
> logengine-web@0.0.0 start /home/bld_csilva/caioquirino/LogEngine/web
> node ./bin/www

module.js:328
    throw err;
    ^

Error: Cannot find module '/home/bld_csilva/caioquirino/LogEngine/web/bin/www'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3

npm ERR! Linux 4.2.5-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v5.3.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! logengine-web@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the logengine-web@0.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the logengine-web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs logengine-web
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls logengine-web
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bld_csilva/caioquirino/LogEngine/web/npm-debug.log

**Comment by iquirino** [comment]
This issue has been solved.
Try using: cd web && node run.

Take a look at web\config.js (webserver port)

Thank you!
